language: python
python:
- 3.6
- 3.5

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jbrid867
  password: Kitten867
    secure: 
ZW9viPRGp//6jRk7qVAwlhngZp1fjr9UELJnhdtZJFe7iKj8D9pIBX8+kP1UfJa3wNegxLmfdae/pLsMn2CGc65pGcuCRrOR4OEOi5CugEbl5Q6nvDe2UQsPZeLGA5bpFXDPu4qdL79D3XyI2Hci4uMSlvTCzq7jCNa9w4gu2YsStlnr26CNWgdciDxCw2pd4UVYykpc8sThDJu+xIG0X9R32m/2dPvVAec0bujjK6tuHjwbji+JjnczwPCZ7TkIxoFS7u7paNrCr/ZFnnRL0oSlJzv7syp/9YY5Nb220fWwEc0sqi8kR78oSyfT2caMlo1Dl7olHU3/aUKpFg/J4DiyHCg25IF8kRtXewpo42kkbxRsA5STsydHp0jGIOjtMkdZLF0hfCxn4Hga+ZDsZvJCQMm6xgRbJIcucNE+Qp4ZfhtMFfPT+mAv7a2VmQh0Q8WH9jI10v0TMfDaG/14LFVVOUncJM99Gh6d81rv3pd/9GWBxSyu+HC9Aez/2lrGQgEXD5SCUd68hTuuzbN4oYrnUy237J4k3Tz1ywEImB0L8Gjchl1ZpPHxrtjNiHbCxp8oQdsXJAfmnxQTLTU3M3iZwg2PQrdB2BjnNqyFAU6rzCNoUGiDcHwwtkmSy39UvQQanbX/IkwL53HmPJnomLIu/jRd6HZFlN9BQuf8qew=
  on:
    tags: true
    repo: jbrid867/simple
    python: 3.6
